"""
transport/models.py - Project ORCA Satellite Communication Schemas
ISRO SIH Problem Statement 176: Marine Multi-Agent System

Defines lightweight, strictly validated Pydantic schemas for offshore satellite
communication messages, bandwidth-optimized compact responses, and message status tracking.
"""

import time
from enum import Enum
from typing import Optional, Dict, Any, Union
from pydantic import BaseModel, Field, field_validator


class SatelliteProtocolVersion(int, Enum):
    V1 = 1


class SatelliteMessageType(str, Enum):
    ORCA_QUERY = "ORCA_QUERY"
    ORCA_PING = "ORCA_PING"
    ORCA_ACK = "ORCA_ACK"


class ProcessingStatus(str, Enum):
    RECEIVED = "RECEIVED"
    PROCESSING = "PROCESSING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class SatellitePayload(BaseModel):
    """
    Compact payload originating from a vessel's mobile client/satellite terminal.
    Contains strict boundary validation to reject malformed or oversized entries.
    """
    query: str = Field(
        ...,
        min_length=1,
        max_length=500,
        description="User query text (compact natural language, max 500 chars to avoid sat bloat)"
    )
    latitude: float = Field(
        ...,
        ge=-90.0,
        le=90.0,
        description="Vessel GPS latitude (-90 to 90 degrees)"
    )
    longitude: float = Field(
        ...,
        ge=-180.0,
        le=180.0,
        description="Vessel GPS longitude (-180 to 180 degrees)"
    )
    persona: Optional[str] = Field(
        "FISHERMAN",
        description="Stakeholder persona (e.g., FISHERMAN, RESEARCHER, MARITIME_AUTHORITY)"
    )
    language: Optional[str] = Field(
        "en",
        description="Language code (ISO 639-1, e.g. en, ta, hi, te, ml, bn)"
    )
    speed_knots: Optional[float] = Field(
        0.0,
        ge=0.0,
        le=100.0,
        description="Vessel speed over ground in knots"
    )
    heading_degrees: Optional[float] = Field(
        120.0,
        ge=0.0,
        le=360.0,
        description="Vessel heading in degrees (0 to 360)"
    )
    gps_accuracy_meters: Optional[float] = Field(
        4.5,
        ge=0.0,
        le=1000.0,
        description="GPS horizontal dilution / accuracy in meters"
    )

    @field_validator("query")
    @classmethod
    def validate_query_not_whitespace(cls, v: str) -> str:
        s = v.strip()
        if not s:
            raise ValueError("Query string cannot be empty or pure whitespace.")
        return s

    model_config = {"extra": "ignore"}


class SatelliteMessage(BaseModel):
    """
    Application-level envelope for satellite requests delivered via provider gateway.
    """
    protocol_version: int = Field(
        1,
        description="Satellite protocol version (strictly 1)"
    )
    message_id: str = Field(
        ...,
        min_length=1,
        max_length=64,
        description="Unique message identifier generated by vessel terminal / client"
    )
    message_type: str = Field(
        SatelliteMessageType.ORCA_QUERY.value,
        description="Message type: ORCA_QUERY | ORCA_PING | ORCA_ACK"
    )
    timestamp: Union[int, float] = Field(
        default_factory=lambda: int(time.time()),
        description="Epoch timestamp in seconds when the message was queued"
    )
    payload: SatellitePayload = Field(
        ...,
        description="Compact operational request payload"
    )

    @field_validator("protocol_version")
    @classmethod
    def validate_version(cls, v: int) -> int:
        if v != 1:
            raise ValueError(f"Unsupported protocol version: {v}. Only protocol_version=1 is supported.")
        return v

    @field_validator("message_id")
    @classmethod
    def validate_message_id(cls, v: str) -> str:
        s = v.strip()
        if not s:
            raise ValueError("message_id cannot be blank.")
        import re
        if not re.match(r"^[a-zA-Z0-9_\-\.:]{1,64}$", s):
            raise ValueError(f"message_id contains invalid characters: '{s}'")
        return s

    model_config = {"extra": "ignore"}


class SatelliteCompactResponse(BaseModel):
    """
    Bandwidth-optimized response designed for high-cost, low-bitrate offshore satellite return links.
    Omits large GeoJSON coordinates, map styling, raw debug traces, and base64 audio.
    """
    protocol_version: int = Field(1, description="Satellite protocol version")
    message_id: str = Field(..., description="Correlated message identifier matching request")
    status: str = Field("SUCCESS", description="SUCCESS | CAUTION | DANGER | ERROR")
    risk: Optional[str] = Field(None, description="Extracted threat status: SAFE, CAUTION, DANGER, NO-GO")
    risk_score: Optional[float] = Field(None, description="Composite risk index (0 to 100)")
    advisory: str = Field(..., description="Concise, actionable operational advisory text")
    latitude: float = Field(..., description="Referenced vessel latitude")
    longitude: float = Field(..., description="Referenced vessel longitude")
    timestamp: Union[int, float] = Field(default_factory=lambda: int(time.time()), description="Response Unix epoch timestamp")
    data_age_minutes: Optional[int] = Field(15, description="Age of newest satellite observation in minutes")
    wave_height_m: Optional[float] = Field(None, description="Significant wave height in meters")
    wind_speed_kmh: Optional[float] = Field(None, description="Surface wind speed in km/h")
    cached: bool = Field(False, description="True if served from idempotency store without agent re-execution")

    model_config = {"extra": "allow"}


class SatelliteMessageRecord(BaseModel):
    """
    Storage record tracking a satellite message through its lifecycle for idempotency and status queries.
    """
    message_id: str
    status: ProcessingStatus = ProcessingStatus.RECEIVED
    received_at: float = Field(default_factory=time.time)
    updated_at: float = Field(default_factory=time.time)
    request_payload: Optional[Dict[str, Any]] = None
    compact_response: Optional[Dict[str, Any]] = None
    error: Optional[str] = None
    retries: int = 0

    model_config = {"extra": "allow"}

